import Head from "next/head";
import styles from "./index.module.css";

import Router from "next/router";

export default function Landing() {
  return (
    <>
      <Head>
        <title>workT3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Work<span className={styles.pinkSpan}>T3</span>
          </h1>
          <div className={styles.cardRow}>
            <button className={styles.card} onClick={() => Router.push("/Login")}>
              <h3 className={styles.cardTitle}>Login</h3>
            </button>
            <button
              className={styles.card}
              onClick={() => Router.push("/Register")}
            >
              <h3 className={styles.cardTitle}>Register</h3>
            </button>
          </div>
          <p className={styles.showcaseText}></p>
        </div>
      </main>
    </>
  );
}
